import './style.css';
import manifestJson from './data/manifest.json';
import sceneEnvJson from './data/sceneEnv.json';
import type { Manifest, SceneInfo, ThemeInfo } from './types';
import { Game } from './engine/Game';
import type { SceneEnv } from './scenery/Environment';
import { lookFor } from './data/themeLooks';
import { Library, type Track } from './music/Library';
import { RadioCard } from './ui/RadioCard';
import { TastePanel } from './ui/TastePanel';
import { ChatPanel } from './ui/ChatPanel';

// App flow: ThemeMenu -> SceneMenu -> Play. The 3D scene is always rendered;
// menus sit on top of a slowly orbiting preview of the hovered theme.
// The current view lives in the URL (#/theme/<id>, #/scene/<id>/<videoId>),
// so a reload or the browser's back button keeps your place.

const manifest = manifestJson as Manifest;
// Sky + world-below per scene, generated by tools/analyze_scenes.py (editable).
const sceneEnv = sceneEnvJson as Record<string, SceneEnv>;
const DEFAULT_ENV: SceneEnv = { time: 'day', below: 'clouds', weather: 'none', skyTop: '#5b8fd6', skyBottom: '#ffd8a8' };
const scenesById = new Map(manifest.scenes.map((s) => [s.id, s]));
const themesById = new Map(manifest.themes.map((t) => [t.id, t]));
const ui = document.getElementById('ui')!;
const game = new Game(document.getElementById('stage')!);
const lib = new Library(manifest);
const chat = new ChatPanel();

const radio = new RadioCard(lib, {
  pick: (t) => playTrack(t, 'push'),
  ended: () => {
    const next = lib.next(true);
    if (next) playTrack(next, 'replace');
    else radio.finished();
  },
  openTaste: () => taste.open(),
});
const taste = new TastePanel(lib, manifest.themes, () => radio.refresh(), () => playMix());

let previewKey = '';
function preview(themeId: string, seed: string) {
  const key = `${themeId}/${seed}`;
  if (key === previewKey) return;
  previewKey = key;
  const scene = scenesById.get(seed);
  game.loadScene(themeId, seed, sceneEnv[seed] ?? DEFAULT_ENV, scene?.video ? `media/${scene.id}/loop.mp4` : undefined);
}

function h<K extends keyof HTMLElementTagNameMap>(tag: K, props: Partial<HTMLElementTagNameMap[K]> = {}, ...children: (Node | string)[]) {
  const el = Object.assign(document.createElement(tag), props);
  el.append(...children);
  return el;
}

function setUrl(hash: string, mode: 'push' | 'replace') {
  if (location.hash === hash) return;
  if (mode === 'push') history.pushState(null, '', hash);
  else history.replaceState(null, '', hash);
}

// ---------------------------------------------------------------- menus

function showThemeMenu() {
  setUrl('#/', 'replace');
  leavePlay();
  const grid = h('div', { className: 'theme-grid' });
  for (const t of manifest.themes) {
    const look = lookFor(t.id);
    const card = h('button', { className: 'theme-card' },
      h('span', { className: 'count', textContent: `${t.scenes.length}` }),
      h('span', { className: 'name', textContent: t.name }),
      h('span', { className: 'tag', textContent: look.tagline }),
    );
    card.style.background = `linear-gradient(160deg, ${look.skyTop}, ${look.skyBottom})`;
    const hover = () => preview(t.id, t.scenes[0]);
    card.addEventListener('mouseenter', hover);
    card.addEventListener('focus', hover);
    card.addEventListener('click', () => {
      setUrl(`#/theme/${t.id}`, 'push');
      showSceneMenu(t);
    });
    grid.append(card);
  }
  const mix = h('button', { className: 'primary', textContent: '▶ Play my mix' });
  mix.onclick = () => playMix();
  const tasteBtn = h('button', { className: 'back', textContent: '⚙ Your taste' });
  tasteBtn.onclick = () => taste.open();
  ui.replaceChildren(h('div', { className: 'menu' }, h('div', { className: 'menu-inner' },
    h('div', { className: 'brand' }, h('h1', { textContent: 'Bear Den Simulator' })),
    h('p', { className: 'sub', textContent: `${manifest.themes.length} themes · ${manifest.scenes.length} scenes · pick a theme, or let the radio choose` }),
    h('div', { className: 'menu-actions' }, mix, tasteBtn),
    grid,
  )));
  if (!previewKey) preview(manifest.themes[0].id, manifest.themes[0].scenes[0]);
}

function showSceneMenu(theme: ThemeInfo) {
  leavePlay();
  preview(theme.id, theme.scenes[0]);
  const list = h('div', { className: 'scene-list' });
  for (const id of theme.scenes) {
    const s = scenesById.get(id)!;
    const meta = h('div', { className: 'meta' });
    if (s.subLabel) meta.append(h('span', { className: 'pill accent', textContent: s.subLabel }));
    if (!s.youtube.length) meta.append(h('span', { className: 'pill', textContent: 'no video yet' }));
    if (s.hasLyrics) meta.append(h('span', { className: 'pill', textContent: 'lyrics' }));
    const thumb = h('img', { className: 'thumb', src: `media/${s.id}/thumb.webp`, alt: '', loading: 'lazy' });
    thumb.onerror = () => (thumb.style.visibility = 'hidden');
    const card = h('button', { className: 'scene-card' }, thumb, h('span', { className: 'title', textContent: s.title }), meta);
    const hover = () => preview(theme.id, s.id);
    card.addEventListener('mouseenter', hover);
    card.addEventListener('focus', hover);
    card.addEventListener('click', () => playScene(s, 'push'));
    list.append(card);
  }
  const back = h('button', { className: 'back', textContent: '← Themes' });
  back.addEventListener('click', () => {
    setUrl('#/', 'push');
    showThemeMenu();
  });
  ui.replaceChildren(h('div', { className: 'menu' }, h('div', { className: 'menu-inner' },
    back,
    h('div', { className: 'brand' }, h('h1', { textContent: theme.name })),
    h('p', { className: 'sub', textContent: lookFor(theme.id).tagline }),
    list,
  )));
}

// ---------------------------------------------------------------- play

// HUD is built once per visit to play mode; travelling between scenes only
// updates its text, so the YouTube iframe is never re-attached (that would reload it).
let hud: { title: HTMLElement; back: HTMLButtonElement } | null = null;

function enterPlay() {
  if (hud) return;
  game.setMode('play');
  const back = h('button', { className: 'back' });
  const title = h('div', { className: 'hud-title' });
  const hint = h('div', { className: 'hint' });
  hint.innerHTML = '<kbd>WASD</kbd> move · <kbd>Shift</kbd> run · click ground to walk · drag to look · <kbd>E</kbd> sit · <kbd>Q</kbd> wave';
  ui.replaceChildren(h('div', { className: 'hud-top' }, back, title), hint, chat.el, radio.el);
  hud = { title, back };
}

function leavePlay() {
  hud = null;
  radio.stop();
  game.setMode('showcase');
}

function showScene(scene: SceneInfo) {
  const theme = themesById.get(scene.theme)!;
  preview(theme.id, scene.id);
  enterPlay();
  hud!.title.textContent = scene.title;
  hud!.back.textContent = `← ${theme.name}`;
  hud!.back.onclick = () => {
    setUrl(`#/theme/${theme.id}`, 'push');
    showSceneMenu(theme);
  };
  chat.setRoom(theme.id, theme.name);
}

function playTrack(track: Track, url: 'push' | 'replace') {
  lib.setCurrent(track);
  setUrl(`#/scene/${track.scene.id}/${track.video.id}`, url);
  showScene(track.scene);
  radio.play(track);
}

function playScene(scene: SceneInfo, url: 'push' | 'replace') {
  const track = lib.trackForScene(scene);
  if (track) return playTrack(track, url);
  setUrl(`#/scene/${scene.id}`, url);
  showScene(scene);
  radio.idle(scene);
}

function playMix() {
  const first = lib.next(false);
  if (first) playTrack(first, 'push');
}

// ---------------------------------------------------------------- routing

function route() {
  const [, kind, id, videoId] = location.hash.split('/');
  if (kind === 'theme' && themesById.has(id)) return showSceneMenu(themesById.get(id)!);
  if (kind === 'scene' && scenesById.has(id)) {
    const track = videoId ? lib.get(`${id}/${videoId}`) : null;
    return track ? playTrack(track, 'replace') : playScene(scenesById.get(id)!, 'replace');
  }
  showThemeMenu();
}

addEventListener('popstate', route);

addEventListener('keydown', (e) => {
  if (e.key !== 'Escape' || game.mode !== 'play') return;
  if (e.target instanceof HTMLInputElement || document.querySelector('dialog[open]')) return;
  hud?.back.click();
});

route();

if (import.meta.env.DEV) Object.assign(window, { game, lib });
